ca_platypus_homepage:
    path:     /
    defaults: { _controller: CAPlatypusBundle:Default:index }

view:
    path:     /{name}/show
    defaults: { _controller: CAPlatypusBundle:CheckerController:view }
